spring.application.name=inventory-service
spring.config.import= configserver:http://localhost:8888

# just changed the central config as profiles. automatically fetches dev profile. or else fetch default profile
# make sure inventory-service-dev.yml must be created in config-server
#spring.profiles.active=dev //TODO: you can also do this from env variables